dist: xenial
language: node_js

install:
  - npm ci

script:
  - npm run build
  - npm run test
  - echo "sleep random number of seconds 1-10 to prevent blockchain collisions" && sleep "$(( ( RANDOM % 10 )  + 1 ))"
  - npm run verify

deploy:
  - provider: script
    script: npx semantic-release
    skip_cleanup: true
    on:
      tags: false
      all_branches: true

env:
  global:
    - secure: I70RtgXxfpjhm4VmnXN/aBMgzSJe0rCrvrZV1YdzXNaeGOo2dNCHtlgHqKWH5OLIsa8/au39fQ7+z+pCRx0bR6A/qQY5NKLMVTlowXU+tEsQocw16B29JmcTxNdWqRIxSnMb+xnmtCrcAUF57nsfWt3+Nu9TyP0Zg3V+b72Ris+Xg+R0EqdTVTeFdNJq2IdVGGkJ5bdYlBG0qURj+8mheNgl3BKMpDhH1BtQE9y0msyQXIZcNfpaEoo8N85aeSLN1sfMxR2S/NgF2b5RudIJv/3XA9e5Y9dHcNhpoWMZEGbMtPVGV3QulkEMDFamKz9Cdw53+LqLzirEolnPxeyENblnkwcr6V63//RFf2YZgd7kSrIc5QqxtYw4jUXd6dEj25wKD8GBFCOW5TAbB2a+k/eewx2FgRH3kL6d0h7QAdob3ulvn62La0LaGaLye8F4L4ecgTbKF6R9V5yABgQjQ6HXbB3YnMa0x6HQv576/iEkO2BhMSJgpiaUEIApOJ3MFSmq1hhAIFwNTPKP1kRWcKzdWHJQPjm2fP86EtqrLnkr+hqeShz9taNeUHxNBGgcUJFqTrf0pFdJVlhRG458NlBa2cBXDnhUDlFUmj2HUMcO+bVUNoPKIxOvHCDlLq18zWpZGv74rV0xWmDC+ICoJTFG9D2K2iqKRqf4jax1hBU=
    - secure: S9Dr6US2TkLKuu0aIsmtwGbjrXRF0sTksKB6o6XKRn2DZKl0MFHrivP7hJPtE81SxQ6TypkcFZ5f8i83UU4q5n2lLBmIhXPkzUWfKvhtpBpRjO/GuXfjRAOh2RDIyyQFLQ3dZnXDj+TPPWeAtkOH5bBAZjin1m2/LcwZUxWoxYz6peivCiYD0CPYZc62aDhrgA/vFs6XQw6QvnshIlodvQY2FvmqFPG4ddJLpbPOJlDtdZ7FDLZergROIKBpFEpfhGZaLYcNTkjKXQ1Un3kL9mKE111zfPjhgH4MxhZgLYRuiIbDnOFzu3dwjLQgBntCEUH1miGngM9g607BmTA+dUS5E2E+DYWqxdsxUgux6AafpKrDgcbiJVDUVJvk2oE7vYQnUbc9KyLWVo5XY/r2O7wvEjV9o+6484eeWE4FwdGhNGoR8MBkantCOzruOAJIaOO0h2fnCXv2uQPx2OKWhkGmtsesjhdu2+SEabNoO/t2Oh6ZXZveU8qixAHhmKtqHLiIJ57EXC8JJ7JYWKzWfetA+NbsYtNnsh1Uhu3Ijac66BxzKSTzH6r4t1WwZYHZCWTrjO9CpbrmUUFvNRRV+KGlU0cBK0Zi/WVlyfDmT7kZwmgqhNRxayTaHmuuH8FcbaO/AOSVfvT8Ee9A64VjbtGQFwNbS70v4/O1uRP/9as=
